linters:
  enable:
    - cyclop
    - exportloopref
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - goimports
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 10
  whitespace:
    multi-func: true
  goimports:
    local-prefixes: xmlcomparator